services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "${PG_HOST_PORT:-5432}:5432"
    volumes:
      - stateway-local-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: stateway
      PGUSER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust

  minio:
    image: quay.io/minio/minio
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: stateway
      MINIO_ROOT_PASSWORD: 1234567890
    volumes:
      - stateway-local-minio:/data

  nats:
    image: nats:latest
    command: ["-js", "-m", "8222", "-sd", "/data"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - stateway-local-nats:/data

volumes:
  stateway-local-postgres:
  stateway-local-minio:
  stateway-local-nats:
