[database.postgres]
host = "127.0.0.1"
port = 5432
user = "postgres"
db_name = "stateway"

[database.clickhouse]
host = "127.0.0.1"
port = 9000
user = "default"
db_name = "stateway"

[broker]
name_prefix = "STATEWAY_"
subject_prefix = "stateway."

[broker.nats]
url = "nats://127.0.0.1:4222"

[gateway]
gateway_count = 1
gateway_id = 0
